### ISSUE TITLE
Development discussion and dashboard

### ISSUE THREAD

**Issue by termoshtt** [termoshtt/ndarray-linalg#29]
Any suggestions are welcome :)

Algorithms to be implemented
------------------------------------
- [ ]  eig: Eigenvalue analysis for general matrix (#40)
- [ ] outer: Outer product
- [x] deth: Determinant for Hermite/Symmetric matrices
- [ ] dmd: [Dynamics mode decomposition](https://en.wikipedia.org/wiki/Dynamic_mode_decomposition)
- [ ] pca: Principal components analysis

**Comment by termoshtt** [comment]
Interpolation algorithm will be helpful
https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html

**Comment by termoshtt** [comment]
ARPACK bindings is necessary to execute large linear problems. 
In Python, the ARPACK binding is served in scipy.sparse.linalg. We can also implement Krylov-subspace based algorithms in Rust as scipy.optimize does.

- https://github.com/garrison/arpack.rs
- https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html
- https://docs.scipy.org/doc/scipy/reference/optimize.html

**Comment by termoshtt** [comment]
assert_parallel!

**Comment by termoshtt** [comment]
not managed

**Comment by NnannaOmoke** [comment]
Outer product has still not been implemented, at least as of v0.16.0
Even though inner product exists, however
