### ISSUE TITLE
assert_close_l2! cannot be called without `use ndarray_linalg::*`

### ISSUE THREAD

**Issue by termoshtt** [termoshtt/ndarray-linalg#72]

**Comment by bluss** [comment]
Just info: Importing macros with regular `use` is a bug -- it's a preview of the future and it was not intended to be a stable feature. Only works in stable with globs.

**Comment by termoshtt** [comment]
Thank info, but this will be due to the lack of `$crate::` prefix in my macros.

**Comment by bluss** [comment]
Ah. I'm sorry, that's my mistake.
